### ISSUE TITLE
Code used in Secret City episode.

### ISSUE THREAD

**Issue by tcdtech** [yandex/smart#2]
Hi,

Code from the file smart/groups.c was used as 'hacker code' in the TV series Secret City. It can be seen in S02E01 at roughly 17 minutes in.

Congratulations, you're famous?

My apologies as this is not an 'issue' as such, but I thought you'd like to know.

**Comment by koct9i** [comment]
I do not see any code there. Do you mean those 0-1 sequences?

And there is no file "smart/groups.c" in this repo.
If you mean kernel/groups.c - this is completely upstream file.

**Comment by AsyncWizard** [comment]
I also saw him in a French rap music clip! 🤓
https://youtu.be/-_xJRH8iPx0?t=184
File looks like: https://github.com/yandex/smart/blob/master/kernel/groups.c

**Comment by 3h6-1** [comment]
That file is also used in the "Hacker Typer" site.

**Comment by bini1988** [comment]
I saw part of `kernel/groups.c` at S01E02 of Invincible (TV Series 2021) at 31:03

**Comment by splankthugger** [comment]
also this code was often used in the series "Person of Interest"
